package main

import (
	"fmt"

	protodbopts "go.linka.cloud/protodb/protodb"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	importPathProtodbService = "go.linka.cloud/protodb-service"
	importPathProtodb        = "go.linka.cloud/protodb"
	importPathProtodbPB      = "go.linka.cloud/protodb/protodb/v1alpha1"
	importPathGrpc           = "google.golang.org/grpc"
	importPathContext        = "context"
	importPathFilters        = "go.linka.cloud/protofilters/filters"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			if len(file.Services) == 0 {
				continue
			}
			if err := generateFile(plugin, file); err != nil {
				return err
			}
		}
		return nil
	})
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) error {
	filename := file.GeneratedFilenamePrefix + "_protodb.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-protodb-service. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P()

	multiple := len(file.Services) > 1
	for _, service := range file.Services {
		if err := generateService(g, file, service, multiple); err != nil {
			return err
		}
		g.P()
	}
	return nil
}

func generateService(g *protogen.GeneratedFile, file *protogen.File, service *protogen.Service, multiple bool) error {
	create := findMethod(service, "Create")
	read := findMethod(service, "Read")
	update := findMethod(service, "Update")
	deleteMethod := findMethod(service, "Delete")
	list := findMethod(service, "List")
	watch := findMethod(service, "Watch")

	resourceMessage := findServiceResource(service, create, read, update, list, watch)
	if resourceMessage == nil {
		return nil
	}

	structName := serviceStructName(service, multiple)
	newFuncName := constructorName(service, multiple)
	watchStreamName := watchStreamTypeName(structName, multiple)

	resourceName := resourceMessage.GoIdent.GoName
	resourcePtr := "*" + resourceName
	resourceKeyPath := "id"
	if path, ok := findKeyPath(resourceMessage); ok {
		resourceKeyPath = dotPath(path)
	}

	protodbService := protogen.GoImportPath(importPathProtodbService)
	protodb := protogen.GoImportPath(importPathProtodb)
	protodbPB := protogen.GoImportPath(importPathProtodbPB)
	grpc := protogen.GoImportPath(importPathGrpc)
	ctxPkg := protogen.GoImportPath(importPathContext)
	filters := protogen.GoImportPath(importPathFilters)

	var (
		createResourceField     *protogen.Field
		createResponseField     *protogen.Field
		readKeyAccessor         string
		readFieldsField         *protogen.Field
		readResponseField       *protogen.Field
		updateResourceField     *protogen.Field
		updateFieldsField       *protogen.Field
		updateResponseField     *protogen.Field
		deleteKeyAccessor       string
		listFilterField         *protogen.Field
		listFieldsField         *protogen.Field
		listPagingField         *protogen.Field
		listLimitField          *protogen.Field
		listOffsetField         *protogen.Field
		listTokenField          *protogen.Field
		listResourcesField      *protogen.Field
		listPagingResponseField *protogen.Field
		listHasNextField        *protogen.Field
		listResponseTokenField  *protogen.Field
		watchFilterField        *protogen.Field
		watchFieldsField        *protogen.Field
		watchOldField           *protogen.Field
		watchNewField           *protogen.Field
		watchTypeField          *protogen.Field
		watchTypeEnum           *protogen.Enum
	)

	createOK := false
	if create != nil {
		createResourceField, _ = findMessageField(create.Input, resourceMessage)
		createResponseField, _ = findMessageField(create.Output, resourceMessage)
		createOK = createResourceField != nil && createResponseField != nil
	}

	readOK := false
	if read != nil {
		readKeyAccessor = findRequestKeyAccessor(read.Input, resourceMessage)
		readFieldsField = findFieldByName(read.Input, "fields")
		readResponseField, _ = findMessageField(read.Output, resourceMessage)
		readOK = readKeyAccessor != "" && readResponseField != nil
	}

	updateOK := false
	if update != nil {
		updateResourceField, _ = findMessageField(update.Input, resourceMessage)
		updateFieldsField = findFieldByName(update.Input, "fields")
		updateResponseField, _ = findMessageField(update.Output, resourceMessage)
		updateOK = updateResourceField != nil && updateResponseField != nil
	}

	deleteOK := false
	if deleteMethod != nil {
		deleteKeyAccessor = findRequestKeyAccessor(deleteMethod.Input, resourceMessage)
		deleteOK = deleteKeyAccessor != ""
	}

	listOK := false
	if list != nil {
		listFilterField = findFieldByName(list.Input, "filter")
		listFieldsField = findFieldByName(list.Input, "fields")
		listPagingField = findFieldByName(list.Input, "paging")
		listLimitField = findFieldByName(list.Input, "limit")
		listOffsetField = findFieldByName(list.Input, "offset")
		listTokenField = findFieldByName(list.Input, "token")
		listResourcesField, _ = findRepeatedMessageField(list.Output, resourceMessage)
		listPagingResponseField = findFieldByName(list.Output, "paging")
		listHasNextField = findFieldByName(list.Output, "has_next")
		listResponseTokenField = findFieldByName(list.Output, "token")
		listOK = listResourcesField != nil
	}

	watchOK := false
	if watch != nil {
		watchFilterField = findFieldByName(watch.Input, "filter")
		watchFieldsField = findFieldByName(watch.Input, "fields")
		watchOldField = findFieldByName(watch.Output, "old")
		watchNewField = findFieldByName(watch.Output, "new")
		watchTypeField = findFieldByName(watch.Output, "type")
		if watchTypeField != nil {
			watchTypeEnum = watchTypeField.Enum
		}
		watchOK = watchOldField != nil && watchNewField != nil && watchTypeField != nil && watchTypeEnum != nil
	}

	methodsGenerated := 0
	for _, ok := range []bool{createOK, readOK, updateOK, deleteOK, listOK, watchOK} {
		if ok {
			methodsGenerated++
		}
	}
	if methodsGenerated == 0 {
		return nil
	}

	g.P("var _ ", service.GoName, "Server = (*", structName, ")(nil)")
	g.P()

	g.P("func ", newFuncName, "(db ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "DB", GoImportPath: protodb}), ", opts ...", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Option", GoImportPath: protodbService}), "[", resourceName, ", ", resourcePtr, "]) *", structName, " {")
	if resourceKeyPath == "id" {
		g.P("\treturn &", structName, "{Service: ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "New", GoImportPath: protodbService}), "[", resourceName, ", ", resourcePtr, "](db, opts...)}")
	} else {
		g.P("\treturn &", structName, "{Service: ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "New", GoImportPath: protodbService}), "[", resourceName, ", ", resourcePtr, "](db, append([]", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Option", GoImportPath: protodbService}), "[", resourceName, ", ", resourcePtr, "]{", g.QualifiedGoIdent(protogen.GoIdent{GoName: "WithKeyPath", GoImportPath: protodbService}), "[", resourceName, ", ", resourcePtr, "](", fmt.Sprintf("%q", resourceKeyPath), ")}, opts...)...)}")
	}
	g.P("}")
	g.P()

	g.P("type ", structName, " struct {")
	g.P("\tUnimplemented", service.GoName, "Server")
	g.P("\tService ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Service", GoImportPath: protodbService}), "[", resourceName, ", ", resourcePtr, "]")
	g.P("}")
	g.P()

	if createOK {
		g.P("func (s *", structName, ") Create(ctx ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Context", GoImportPath: ctxPkg}), ", request *", create.Input.GoIdent.GoName, ") (*", create.Output.GoIdent.GoName, ", error) {")
		g.P("\tres, err := s.Service.Create(ctx, request.", createResourceField.GoName, ")")
		g.P("\tif err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\treturn &", create.Output.GoIdent.GoName, "{", createResponseField.GoName, ": res}, nil")
		g.P("}")
		g.P()
	}

	if readOK {
		g.P("func (s *", structName, ") Read(ctx ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Context", GoImportPath: ctxPkg}), ", request *", read.Input.GoIdent.GoName, ") (*", read.Output.GoIdent.GoName, ", error) {")
		if readFieldsField != nil {
			g.P("\tres, err := s.Service.Read(ctx, ", readKeyAccessor, ", request.", readFieldsField.GoName, ")")
		} else {
			g.P("\tres, err := s.Service.Read(ctx, ", readKeyAccessor, ", nil)")
		}
		g.P("\tif err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\treturn &", read.Output.GoIdent.GoName, "{", readResponseField.GoName, ": res}, nil")
		g.P("}")
		g.P()
	}

	if updateOK {
		g.P("func (s *", structName, ") Update(ctx ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Context", GoImportPath: ctxPkg}), ", request *", update.Input.GoIdent.GoName, ") (*", update.Output.GoIdent.GoName, ", error) {")
		if updateFieldsField != nil {
			g.P("\tres, err := s.Service.Update(ctx, request.", updateResourceField.GoName, ", request.", updateFieldsField.GoName, ")")
		} else {
			g.P("\tres, err := s.Service.Update(ctx, request.", updateResourceField.GoName, ", nil)")
		}
		g.P("\tif err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\treturn &", update.Output.GoIdent.GoName, "{", updateResponseField.GoName, ": res}, nil")
		g.P("}")
		g.P()
	}

	if deleteOK {
		g.P("func (s *", structName, ") Delete(ctx ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Context", GoImportPath: ctxPkg}), ", request *", deleteMethod.Input.GoIdent.GoName, ") (*", deleteMethod.Output.GoIdent.GoName, ", error) {")
		g.P("\tif err := s.Service.Delete(ctx, ", deleteKeyAccessor, "); err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\treturn &", deleteMethod.Output.GoIdent.GoName, "{}, nil")
		g.P("}")
		g.P()
	}

	if listOK {
		g.P("func (s *", structName, ") List(ctx ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Context", GoImportPath: ctxPkg}), ", request *", list.Input.GoIdent.GoName, ") (*", list.Output.GoIdent.GoName, ", error) {")
		if listFilterField != nil {
			g.P("\tfilter := request.", listFilterField.GoName)
			g.P("\tif filter == nil {")
			g.P("\t\tfilter = &", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Expression", GoImportPath: filters}), "{}")
			g.P("\t}")
		} else {
			g.P("\tfilter := &", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Expression", GoImportPath: filters}), "{}")
		}
		if listHasNextField != nil {
			g.P("\tvar hasNext bool")
		}
		if listResponseTokenField != nil {
			g.P("\tvar pageToken string")
		}
		g.P("\tvar paging *", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Paging", GoImportPath: protodbPB}))
		if listLimitField != nil || listOffsetField != nil || listTokenField != nil {
			g.P("\tpaging = &", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Paging", GoImportPath: protodbPB}), "{")
			if listLimitField != nil {
				g.P("\t\tLimit: request.", listLimitField.GoName, ",")
			}
			if listOffsetField != nil {
				g.P("\t\tOffset: request.", listOffsetField.GoName, ",")
			}
			if listTokenField != nil {
				g.P("\t\tToken: request.", listTokenField.GoName, ",")
			}
			g.P("\t}")
		} else if listPagingField != nil {
			g.P("\tpaging = request.", listPagingField.GoName)
		}
		usePagingInfo := listPagingResponseField != nil || listHasNextField != nil || listResponseTokenField != nil
		if usePagingInfo {
			if listFieldsField != nil {
				g.P("\tres, info, err := s.Service.List(ctx, filter, request.", listFieldsField.GoName, ", paging)")
			} else {
				g.P("\tres, info, err := s.Service.List(ctx, filter, nil, paging)")
			}
		} else if listFieldsField != nil {
			g.P("\tres, _, err := s.Service.List(ctx, filter, request.", listFieldsField.GoName, ", paging)")
		} else {
			g.P("\tres, _, err := s.Service.List(ctx, filter, nil, paging)")
		}
		g.P("\tif err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		if listHasNextField != nil {
			g.P("\tif info != nil {")
			g.P("\t\thasNext = info.HasNext")
			if listResponseTokenField != nil {
				g.P("\t\tpageToken = info.Token")
			}
			g.P("\t}")
		} else if listResponseTokenField != nil {
			g.P("\tif info != nil {")
			g.P("\t\tpageToken = info.Token")
			g.P("\t}")
		}
		g.P("\treturn &", list.Output.GoIdent.GoName, "{")
		g.P("\t\t", listResourcesField.GoName, ": res,")
		if listPagingResponseField != nil {
			g.P("\t\t", listPagingResponseField.GoName, ": info,")
		}
		if listHasNextField != nil {
			g.P("\t\t", listHasNextField.GoName, ": hasNext,")
		}
		if listResponseTokenField != nil {
			g.P("\t\t", listResponseTokenField.GoName, ": pageToken,")
		}
		g.P("\t}, nil")
		g.P("}")
		g.P()
	}

	if watchOK {
		g.P("func (s *", structName, ") Watch(request *", watch.Input.GoIdent.GoName, ", stream ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "ServerStreamingServer", GoImportPath: grpc}), "[", watch.Output.GoIdent.GoName, "]) error {")
		if watchFilterField != nil {
			g.P("\tfilter := request.", watchFilterField.GoName)
			g.P("\tif filter == nil {")
			g.P("\t\tfilter = &", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Expression", GoImportPath: filters}), "{}")
			g.P("\t}")
		} else {
			g.P("\tfilter := &", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Expression", GoImportPath: filters}), "{}")
		}
		if watchFieldsField != nil {
			g.P("\treturn s.Service.Watch(filter, request.", watchFieldsField.GoName, ", &", watchStreamName, "{ServerStreamingServer: stream})")
		} else {
			g.P("\treturn s.Service.Watch(filter, nil, &", watchStreamName, "{ServerStreamingServer: stream})")
		}
		g.P("}")
		g.P()

		g.P("var _ ", g.QualifiedGoIdent(protogen.GoIdent{GoName: "ServerStreamingServer", GoImportPath: grpc}), "[", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Event", GoImportPath: protodbService}), "[", resourceName, ", ", resourcePtr, "]] = (*", watchStreamName, ")(nil)")
		g.P()
		g.P("type ", watchStreamName, " struct {")
		g.P("\t", g.QualifiedGoIdent(protogen.GoIdent{GoName: "ServerStreamingServer", GoImportPath: grpc}), "[", watch.Output.GoIdent.GoName, "]")
		g.P("}")
		g.P()

		g.P("func (w *", watchStreamName, ") Send(ev *", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Event", GoImportPath: protodbService}), "[", resourceName, ", ", resourcePtr, "]) error {")
		g.P("\treturn w.ServerStreamingServer.Send(&", watch.Output.GoIdent.GoName, "{")
		g.P("\t\t", watchTypeField.GoName, ": ", watchTypeEnum.GoIdent.GoName, "(ev.Type),")
		g.P("\t\t", watchOldField.GoName, ": ev.Old,")
		g.P("\t\t", watchNewField.GoName, ": ev.New,")
		g.P("\t})")
		g.P("}")
	}

	return nil
}

func findServiceResource(service *protogen.Service, create, read, update, list, watch *protogen.Method) *protogen.Message {
	if create != nil {
		if _, msg, err := findResourceField(create.Input); err == nil {
			return msg
		}
	}
	if update != nil {
		if field := findFirstMessageField(update.Input); field != nil {
			return field.Message
		}
	}
	if read != nil {
		if field := findFirstMessageField(read.Output); field != nil {
			return field.Message
		}
	}
	if list != nil {
		if field := findFirstRepeatedMessageField(list.Output); field != nil {
			return field.Message
		}
	}
	if watch != nil {
		if field := findFieldByName(watch.Output, "new"); field != nil && field.Message != nil {
			return field.Message
		}
		if field := findFieldByName(watch.Output, "old"); field != nil && field.Message != nil {
			return field.Message
		}
	}
	return nil
}

func findFirstMessageField(message *protogen.Message) *protogen.Field {
	for _, field := range message.Fields {
		if field.Message != nil {
			return field
		}
	}
	return nil
}

func findFirstRepeatedMessageField(message *protogen.Message) *protogen.Field {
	for _, field := range message.Fields {
		if field.Message != nil && field.Desc.Cardinality() == protoreflect.Repeated {
			return field
		}
	}
	return nil
}

func findMethod(service *protogen.Service, name string) *protogen.Method {
	for _, method := range service.Methods {
		if string(method.Desc.Name()) == name {
			return method
		}
	}
	return nil
}

func findFieldByName(message *protogen.Message, name string) *protogen.Field {
	for _, field := range message.Fields {
		if string(field.Desc.Name()) == name {
			return field
		}
	}
	return nil
}

func findRequestKeyAccessor(request *protogen.Message, resource *protogen.Message) string {
	if request == nil || resource == nil {
		return ""
	}
	if path, ok := findKeyPath(resource); ok {
		if accessor, ok := accessorForPath(request, path); ok {
			return accessor
		}
		leaf := path[len(path)-1]
		if field := findFieldByName(request, leaf); field != nil {
			return "request." + field.GoName
		}
	}
	for _, name := range []string{"id", "key", "name"} {
		if field := findFieldByName(request, name); field != nil {
			return "request." + field.GoName
		}
	}
	return ""
}

func accessorForPath(message *protogen.Message, names []string) (string, bool) {
	if message == nil || len(names) == 0 {
		return "", false
	}
	current := message
	accessor := "request"
	for i, name := range names {
		field := findFieldByName(current, name)
		if field == nil {
			return "", false
		}
		accessor += "." + field.GoName
		if i == len(names)-1 {
			if field.Message != nil || field.Desc.IsMap() || field.Desc.Cardinality() == protoreflect.Repeated {
				return "", false
			}
			return accessor, true
		}
		if field.Message == nil || field.Desc.IsMap() || field.Desc.Cardinality() == protoreflect.Repeated {
			return "", false
		}
		current = field.Message
	}
	return "", false
}

func findKeyPath(message *protogen.Message) ([]string, bool) {
	if message == nil {
		return nil, false
	}
	stack := map[protoreflect.FullName]bool{message.Desc.FullName(): true}
	path, ok := findKeyPathIn(message, nil, stack)
	if !ok {
		return nil, false
	}
	names := make([]string, 0, len(path))
	for _, field := range path {
		names = append(names, string(field.Desc.Name()))
	}
	return names, true
}

func dotPath(path []string) string {
	out := ""
	for i, part := range path {
		if i != 0 {
			out += "."
		}
		out += part
	}
	return out
}

func findKeyPathIn(message *protogen.Message, path []*protogen.Field, stack map[protoreflect.FullName]bool) ([]*protogen.Field, bool) {
	for _, field := range message.Fields {
		next := make([]*protogen.Field, 0, len(path)+1)
		next = append(next, path...)
		next = append(next, field)
		if isExplicitKey(field) {
			return next, true
		}
		if field.Message == nil || field.Desc.IsMap() || field.Desc.Cardinality() == protoreflect.Repeated {
			continue
		}
		name := field.Message.Desc.FullName()
		if stack[name] {
			continue
		}
		stack[name] = true
		if nested, ok := findKeyPathIn(field.Message, next, stack); ok {
			return nested, true
		}
		delete(stack, name)
	}
	return nil, false
}

func isExplicitKey(field *protogen.Field) bool {
	if field == nil {
		return false
	}
	options, ok := field.Desc.Options().(*descriptorpb.FieldOptions)
	if !ok {
		return false
	}
	v := proto.GetExtension(options, protodbopts.E_Key)
	if v == nil {
		return false
	}
	b, ok := v.(bool)
	if !ok {
		return false
	}
	return b
}

func findResourceField(message *protogen.Message) (*protogen.Field, *protogen.Message, error) {
	var candidate *protogen.Field
	for _, field := range message.Fields {
		if field.Message == nil {
			continue
		}
		if string(field.Desc.Name()) == "resource" {
			return field, field.Message, nil
		}
		if candidate == nil {
			candidate = field
		}
	}
	if candidate == nil {
		return nil, nil, fmt.Errorf("create request must contain resource message")
	}
	return candidate, candidate.Message, nil
}

func findMessageField(message *protogen.Message, msg *protogen.Message) (*protogen.Field, error) {
	for _, field := range message.Fields {
		if field.Message == msg {
			return field, nil
		}
	}
	return nil, fmt.Errorf("message %s must contain %s field", message.GoIdent.GoName, msg.GoIdent.GoName)
}

func findRepeatedMessageField(message *protogen.Message, msg *protogen.Message) (*protogen.Field, error) {
	for _, field := range message.Fields {
		if field.Message == msg && field.Desc.Cardinality() == protoreflect.Repeated {
			return field, nil
		}
	}
	return nil, fmt.Errorf("message %s must contain repeated %s field", message.GoIdent.GoName, msg.GoIdent.GoName)
}

func serviceStructName(service *protogen.Service, multiple bool) string {
	if !multiple {
		return "DefaultService"
	}
	return "Default" + service.GoName + "Service"
}

func constructorName(service *protogen.Service, multiple bool) string {
	if !multiple {
		return "NewDefaultService"
	}
	return "NewDefault" + service.GoName + "Service"
}

func watchStreamTypeName(structName string, multiple bool) string {
	if !multiple {
		return "watchResponseStream"
	}
	return structName + "WatchResponseStream"
}
