// Code generated by protoc-gen-protodb-service. DO NOT EDIT.
package resource

import (
	context "context"
	protodb "go.linka.cloud/protodb"
	protodb_service "go.linka.cloud/protodb-service"
	pb "go.linka.cloud/protodb/pb"
	filters "go.linka.cloud/protofilters/filters"
	grpc "google.golang.org/grpc"
)

var _ ResourceServiceServer = (*DefaultService)(nil)

func NewDefaultService(db protodb.DB, opts ...protodb_service.Option[Resource, *Resource]) *DefaultService {
	return &DefaultService{Service: protodb_service.New[Resource, *Resource](db, opts...)}
}

type DefaultService struct {
	UnimplementedResourceServiceServer
	Service protodb_service.Service[Resource, *Resource]
}

func (s *DefaultService) Create(ctx context.Context, request *CreateRequest) (*CreateResponse, error) {
	res, err := s.Service.Create(ctx, request.Resource)
	if err != nil {
		return nil, err
	}
	return &CreateResponse{Resource: res}, nil
}

func (s *DefaultService) Read(ctx context.Context, request *ReadRequest) (*ReadResponse, error) {
	res, err := s.Service.Read(ctx, request.ID, request.Fields)
	if err != nil {
		return nil, err
	}
	return &ReadResponse{Resource: res}, nil
}

func (s *DefaultService) Update(ctx context.Context, request *UpdateRequest) (*UpdateResponse, error) {
	res, err := s.Service.Update(ctx, request.Resource, request.Fields)
	if err != nil {
		return nil, err
	}
	return &UpdateResponse{Resource: res}, nil
}

func (s *DefaultService) Delete(ctx context.Context, request *DeleteRequest) (*DeleteResponse, error) {
	if err := s.Service.Delete(ctx, request.ID); err != nil {
		return nil, err
	}
	return &DeleteResponse{}, nil
}

func (s *DefaultService) List(ctx context.Context, request *ListRequest) (*ListResponse, error) {
	filter := request.Filter
	if filter == nil {
		filter = &filters.Expression{}
	}
	var hasNext bool
	var pageToken string
	var paging *pb.Paging
	paging = &pb.Paging{
		Limit:  request.Limit,
		Offset: request.Offset,
		Token:  request.Token,
	}
	res, info, err := s.Service.List(ctx, filter, request.Fields, paging)
	if err != nil {
		return nil, err
	}
	if info != nil {
		hasNext = info.HasNext
		pageToken = info.Token
	}
	return &ListResponse{
		Resources: res,
		HasNext:   hasNext,
		Token:     pageToken,
	}, nil
}

func (s *DefaultService) Watch(request *WatchRequest, stream grpc.ServerStreamingServer[WatchResponse]) error {
	filter := request.Filter
	if filter == nil {
		filter = &filters.Expression{}
	}
	return s.Service.Watch(filter, request.Fields, &watchResponseStream{ServerStreamingServer: stream})
}

var _ grpc.ServerStreamingServer[protodb_service.Event[Resource, *Resource]] = (*watchResponseStream)(nil)

type watchResponseStream struct {
	grpc.ServerStreamingServer[WatchResponse]
}

func (w *watchResponseStream) Send(ev *protodb_service.Event[Resource, *Resource]) error {
	return w.ServerStreamingServer.Send(&WatchResponse{
		Type: WatchResponseType(ev.Type),
		Old:  ev.Old,
		New:  ev.New,
	})
}
